### ISSUE TITLE
Buggy beads when using home and end

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-pairs#106]
There are several buggy scenarios that pop up when using the `home` and `end` keys. 

- The grabbed bead is no longer the first in the series of moving beads.
- When moving a large group of beads across the separator they get completely jumbled up.

**Comment by marlitas** [comment]
This issue became rather intertwined with this issue: https://github.com/phetsims/number-pairs/issues/84

@pixelzoom can you review the `home` and `end` handling for keyboard as well as `handleBeadMove` in `BeadsOnWireNode`?

**Comment by catherinecarter** [comment]
I was looking at the keyboard help dialog and decided to try out `home` and `end` to think about how to refine/confirm the keyboard help dialog. Here's a video of what I saw. If you turn the sound on the video, you can hear me talking through my actions.

There are two things to pay attention to in the video: 
1. The sound of the up/down arrows for the spinners sounds doubled. In the video, I pressed and held the arrows and didn't let go until after the sound was done.
2. The beads were doing strange things using keyboard in both their location and the addend values.

https://github.com/user-attachments/assets/5048de03-aff9-4bb3-915d-15cccad6c9b5

**Comment by marlitas** [comment]
I think this came from me probably having an outdated transpiler on Friday/ this weekend. I fixed the main bug and then found another underlying issue in the Sum Screen. I believe that has been handled, however it does solidify that multitouch is not supported with the beads. In this case specifically when a bead is being dragged and a bead is also being added or removed. Over to @catherinecarter. Let's keep this open for QA.

**Comment by pixelzoom** [comment]
Self assigning, because in https://github.com/phetsims/number-pairs/issues/84#issuecomment-2686488132 @marlitas said:

> Please review: https://github.com/phetsims/number-pairs/issues/106 alongside this one.

**Comment by catherinecarter** [comment]
I will keep trying to reproduce the bug. In the meantime, removing multitouch from the beads seems acceptable to me.

**Comment by pixelzoom** [comment]
The last time that @marlitas and I spoke about this issue, I was under the impression that support for Home/End was going to be dropped, because of the complexity.  But she found a workaround, see https://github.com/phetsims/number-pairs/commit/771f3d68197443ca4011af4ab08b2f7c7c7f1916, which is what I've reviewed. And Home/End still might be dropped if QA finds problems. That said...

About the review.... The changes look good.  BeadsOnWireNode is a beast, especially `handleBeadMove`. @marlitas has done a nice job of documenting and factoring out helper functions. I unfortunately don't have recommendations for simplify further -- the implementation complexity is a symptom supporting the desired interactions for pointer and keyboard. 

Back to @marlitas in case there's more to do here.

**Comment by catherinecarter** [comment]
It's still freezing for me, as of 3/10 in the afternoon. I have no clue how to help with debugging since there's nothing in the console when it happens. Is there another console or somewhere to look other than dev tools to see what's happening so I can pass along the info?

**Comment by marlitas** [comment]
@catherinecarter I think the only thing we can do at this point is see if QA can reproduce so that we have a reliable way of iterating on the problem. Otherwise my hands are tied on how to debug... I will keep this open for QA, and make sure it is part of the dev test issue.

**Comment by marlitas** [comment]
We already have issue: https://github.com/phetsims/number-pairs/issues/85 for QA to test. I am going to close this one as completed.
